### ISSUE TITLE
Test vcsim with other vmomi bindings like pyvmomi

### ISSUE THREAD

**Issue by anfernee** [vmware/govmomi#1015]
People should be able to use other bindings like pyvmomi to talk to vcsim, not just govc. How about adding test written in pyvmomi?

**Comment by dougm** [comment]
Most of the issues with pyvmomi against vcsim are because the wsdl required fields are enforced, whereas Go will silently ignore empty fields regardless of there being an `omitempty` tag or not.  It would be helpful if we had a way to enforce the required fields bet set in Go.

The other pyvmomi issues have just been objects/methods that hadn't been implemented yet.  There is a basic rbvmomi test in vcsim.bats, we could add similar for pyvmomi and have CI run them.

**Comment by Akasurde** [comment]
@dougm @anfernee Ansible uses Pyvmomi and vcsim in integration tests, so indirectly testing of vcsim is done. I agree that we should have Pyvmomi tests as well.

**Comment by dougm** [comment]
I don't want to duplicate the testing that Ansible does or bring pyvmomi deps into govmomi.  Let's continue as we have been, fixing pyvmomi specific issues as they come up.  I believe most/all such issues are cases where vcsim is not including required fields.  The unimplemented methods of vcsim are not specific to any particular language.
