### ISSUE TITLE
govc: more params for dvs.portgroup.change

### ISSUE THREAD

**Issue by yrjo** [vmware/govmomi#1053]
Hi,
is there any plan to extend dvs.portgroup.change call for more attributes in any future?

I mean something related to 
config.defaultPortConfig
like eg.
VmwareUplinkPortTeamingPolicy
and so?

cheers!

**Comment by dougm** [comment]
Sure, can you provide more detail / examples on what you want to change?

**Comment by rfdrake** [comment]
I would like to see the some of the features that are available in host.portgroup.change be available in dvs.portgroup.change.  Like being able to set AllowPromiscuous and other flags.

I would also love it if trunk ports could be defined in both the dvs and the host portgroups.  Currently I'm doing this with powercli:

    Get-VDPortgroup -Name $pgname | Set-VDPortgroup -VlanTrunkRange "100,200"

Finally, although this is a different command, I would like it if we could have "dvs.portgroup.remove" so that we can remove portgroups when we're done with them.

**Comment by haydonryan** [comment]
+1 on trunk (and teamed) port groups.  
I noticed here: https://pubs.vmware.com/vsphere-51/index.jsp?topic=%2Fcom.vmware.powercli.cmdletref.doc%2FSet-VirtualPortGroup.html that it mentions using 4095 to enable trunk mode, however this doesn't seem to work with govc...

**Comment by haydonryan** [comment]
Just ran into this again - it would be good to have at least the same features as a host.portgroup.change command. - eg turning on forged commits and promiscuous mode.
