### ISSUE TITLE
Snapshot.tree: format date or filter by date

### ISSUE THREAD

**Issue by simolev** [vmware/govmomi#1128]
I'd like `snapshot.tree` to output dates in the **`YYYY-MM-DD`** format as it's easier to read and parse.
My use case would be to lists and then delete all snapshots in a certain date range:

`govc find -name MyVM | xargs govc snapshot.tree -D -i -vm | sed 's/ *\[//;s/]//' | awk '$2<"2018-05-13" {print $1}' | sort -u`

And eventually add `| xargs govc snapshot.remove`

Other improvements I would appreciate would be:

- [ ] plain listing - no tree
- [ ] no square brackets
- [ ] csv or json output
- [ ] do not list snapshots more than once

**Comment by uncle-fed** [comment]
Similar use case here. Biggest issue by far is the date formatting in the `snapshot.tree` output.
It is pretty much unusable in its current form (`year` is completely missing!).
Also -json option has no effect on the `snapshot.tree`.

This currently ends up in a workaround that tries to fetch a complete JSON `Snapshot` object (using `vm.info`) that needs to be recursively parsed (since it's a tree) to extract necessary data out of it. Which really complicates it for a simple use case: "get me a list of all snapshots with the date, comment, and ideally size on disk too".

It would be already helpful if the `snapshot.tree` output could be proper "machine readable", i.e. csv or json like and preferably without a recursion (at least the `csv` version) with the ISO / JSON date format.

Thank you for your time!
