### ISSUE TITLE
ClusterComputeResource missing a lot of methods

### ISSUE THREAD

**Issue by junkao** [vmware/govmomi#1147]
ClusterComputeResource missing a lot of methods
like GetResourceUsage and PlaceVm etc..

**Comment by dougm** [comment]
The generated code for these methods are there, for example: https://github.com/vmware/govmomi/blob/7736cdc786f6d1a3a5110a717c361e65d4d00b16/vim25/methods/methods.go#L5834

The `object.ComputeResource` methods are just convenience wrappers around the generated code, PRs are welcome for that.  Otherwise, the generated methods can also be used directly.
