### ISSUE TITLE
vcsim custom 'state' definition

### ISSUE THREAD

**Issue by jakerobinson** [vmware/govmomi#1185]
I'd like to define a custom state of a simulator instance (e.g. datacenters, networks, VMs, hosts) so that I don't have to remove the defaults and add my own at runtime. This would allow me to mimic what I have in my physical lab or even in production, and test different scenarios very quickly.

**Comment by dougm** [comment]
`vcsim -dc 0` and your inventory is empty

Or `vcsim -vm 0` if you want everything except VMs.  Similar for the other types.
The flags are hooked up to the `Model` fields, we could have an option to specify in a file instead of the switches: https://github.com/vmware/govmomi/blob/8d973c31513ae5f16bdcf5d88c1b8ae2267bc63d/simulator/model.go#L45-L80

**Comment by dougm** [comment]
The related flags:
```
% vcsim -h
Usage of vcsim:
  -app int
        Number of virtual apps per compute resource
  -cluster int
        Number of clusters (default 1)
  -dc int
        Number of datacenters (default 1)
  -ds int
        Number of local datastores (default 1)
  -folder int
        Number of folders
  -host int
        Number of hosts per cluster (default 3)
  -pg int
        Number of port groups (default 1)
  -pod int
        Number of storage pods per datacenter
  -pool int
        Number of resource pools per compute resource
  -standalone-host int
        Number of standalone hosts (default 1)
  -vm int
        Number of virtual machines per resource pool (default 2)
```

**Comment by dougm** [comment]
@jakerobinson do the flags above provide what you need?
