### ISSUE TITLE
Alternative to storing username and password in clear text?

### ISSUE THREAD

**Issue by tarminator** [vmware/govmomi#1236]
Is there an alternative to call a local SSH user account with key exchange configured between the host and Vsphere endpoint for this provider instead of adding a username and password in clear text to file in a global configuration directory on each server?  I would expect a security audit to pick up on something like this.

**Comment by dougm** [comment]
govmomi does not require credentials to be stored in a text file.. can you provide more context here?

There are also alternative authentication methods: https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#sessionlogin

**Comment by tarminator** [comment]
Hi Dougm, I'm researching vmware storage integration with Openshift and the doc link below explains the setup process for context.
https://docs.okd.io/latest/install_config/configuring_vsphere.html#vsphere-enabling
As per the link you shared there appears to be secure options available. Maybe the issue is how the credentials are stored and called by the provider?

**Comment by dougm** [comment]
Right, the vsphere cloud provider supports SAML token auth and also supports Kubernetes secrets. I don't know if that applies yet to Openshift, but in any case this would be a Kubernetes/Openshift issue rather than govmomi.

https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/saml-token-authentication.html

https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html
