### ISSUE TITLE
credentials via container secrets

### ISSUE THREAD

**Issue by rockaut** [vmware/govmomi#1352]
In swarm and kubernetes it's possible to securely manage credentials directly and map them to containers as files. It would be great if we can use these mechanisms somehow.

Maybe through an ENV variable like GOVC_SECRETFILE which overrides GOVC_PASSWORD. Also it would be nicer if govc env command DON'T actually shows the sensitive password variables.

**Comment by dougm** [comment]
Not sure about taking on the dependencies to support this in govc.  Can you provide more specific doc/code pointers to the mechanisms you're referring to?

Another option might be integration with desktop mechanisms such as OSX Keychain and/or Linux (GNOME?) Keyring, etc.

**Comment by dougm** [comment]
ok, I had something like NaCl in mind (https://godoc.org/golang.org/x/crypto/nacl/secretbox) regarding the deps.  Didn't realize these types of secrets were exposed as literals within a file.  In that case, rather than add a new flag+env var, how about if `GOVC_PASSWORD` is set to a file we just source the contents?

We can also mask the `govc env` output, but there are scripts that depend on the current behavior.

**Comment by rockaut** [comment]
You mean like ```GOVC_PASSWORD=/var/secrets/password```? Sounds great and should do the trick. But please also for GOVC_USERNAME.

Ad env. I understand that there might be dependency on that currently. Should i extract it from here to another new issue to discuss there? I just wanted to bring up if others see that as problem too.

**Comment by dougm** [comment]
@rockaut haven't forgotten about this, we are discussing similar for vcsim in #1489 
No need to open a separate issue.
