### ISSUE TITLE
vm.create fails if read privilege on distributedVirtualSwitch isn't granted

### ISSUE THREAD

**Issue by lqb** [vmware/govmomi#1517]
Running `./govc vm.create -debug -net 'VDI Network 10.XXX.XXX.x' -pool 3-Low -ds XXXXX -folder XXXXXX vm01`
doesn't work. The error message is:
`./govc: no System.Read privilege on: DistributedVirtualPortgroup:dvportgroup--708.config.distributedVirtualSwitch`

If read permissions are granted, it works. 
Creating a virtual machine from WebGUI works without read permissions.

Shouldn't it work without read permission with govc?
If not, why is the read permission needed?

Thanks

**Comment by dougm** [comment]
I don't know how the GUI avoids it, but the govmomi code is here: https://github.com/vmware/govmomi/blob/35d0b7d3d2f6ddb02af246d2e0285e5c23aa9850/object/distributed_virtual_portgroup.go#L43-L52

We need those properties for the network backing: https://github.com/vmware/govmomi/blob/35d0b7d3d2f6ddb02af246d2e0285e5c23aa9850/object/distributed_virtual_portgroup.go#L60-L61

**Comment by gwesterfieldjr** [comment]
What did you need to set the read permissions on ?

**Comment by dougm** [comment]
@gwesterfieldjr @lqb were you able to resolve this?

We are also discussing here: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/710#issuecomment-571818267

**Comment by dougm** [comment]
In looking at this again for kubernetes-sigs/cluster-api-provider-vsphere#710 , I still don't see anything we can do on the govmomi side to avoid.  And as @sheriefhammam confirmed, granting System.Read privilege on the Switch fixes the issue.

I am going to open a PR that (hopefully) clears up the error message in this case, as it had sounded like a permission issue with the DVPG itself, rather than the Switch.
