### ISSUE TITLE
Resource Configs for Objects

### ISSUE THREAD

**Issue by tibmeister** [vmware/govmomi#1658]
Is it possible to set resource configurations for the objects?  For instance, can I say I want the hosts to report they have 32GB RAM and 4 CPU?  It would be helpful to allow me to simulate this for some work I'm doing to validate some math I'm performing for capacity planning.

**Comment by dougm** [comment]
Are you referring to vcsim?  If so, the record/playback feature can help, once its merged: #1623 
If you don't need the vcsim binary, and are writing tests in Go, you can modify the objects directly.
I can put some examples together either way.

**Comment by tibmeister** [comment]
Record/playback?  I will need to look at that.  I'm not using Go, so unfortunately that doesn't help much but maybe one day I will learn Go, another language to add to the arsenal I guess.

**Comment by dougm** [comment]
Here's an example if you want to try it out: https://github.com/vmware/govmomi/wiki/vcsim-features#modifying-saved-inventory

You'll need to build govc and vcsim from the master branch: https://github.com/vmware/govmomi/blob/master/govc/README.md#source

Also note the feature is brand new.  We plan to make it possible to save a subset of inventory, rather than everything, but that still needs some work.  Any feedback is welcome too of course.
