### ISSUE TITLE
regression: vm clone failed

### ISSUE THREAD

**Issue by nanw1103** [vmware/govmomi#1712]
Command being used:
govc vm.clone -waitip=true -on=true -vm /nanw/vm/hlcm-build/hlcm-deployer-build-base hlcm-deployer

Works with 0.21
Fails with: v0.21.0-58-g8d28646
Fails with: master build 0.22

Error message in vCenter: 
Task Name: Call DRS for cross vMotion placement recommendations
Status: The operation is not allowed in the current state.

I think this is related to the target cluster state, which has one and only one host without DRS enabled.

**Comment by dougm** [comment]
What environment variables do you have set?  In this case, if GOVC_CLUSTER is set, that could be the issue.  That is the only related change to `vm.clone` since 0.21: https://github.com/vmware/govmomi/pull/1589

Either way, I think we'll need to use a different flag name or ignore the env var to include the placement feature that #1589 introduced, so we avoiding changing behavior if GOVC_CLUSTER was already set.

**Comment by dougm** [comment]
#1714 should fix the issue for you.
