### ISSUE TITLE
govc import.ova requires resource group

### ISSUE THREAD

**Issue by driftavalli** [vmware/govmomi#1760]
I am trying to create a template using import.ova but it seems there's a hard requirement on resource groups, we don't use DRS or resource group and I was wondering if is possible to import and create a template just specifying a datastore.

**Comment by dougm** [comment]
The vSphere API requires a ResourcePool param.  If your environment only has 1 ResourcePool, govc will use that by default.  Otherwise you need to specific `-pool` or `-host`.  See pools using:

```console
% govc find / -type p
```

In your case, you can automate the `-host` choice using:

```console
% govc find . -type m -datastore $(govc find -i datastore -name vsanDatastore) | head -1
```
Maybe we could bake something like that into the command if `MarkAsTemplate == true`.

**Comment by driftavalli** [comment]
Yes, using the default resource pool would be helpful. Regarding the "options" parameter, where can one find all the possible terms that can be specified?

**Comment by dougm** [comment]
@driftavalli `govc import.spec path-to-your.ova | jq .` will show you all options for the given ovf or ova.

**Comment by driftavalli** [comment]
Thanks.
