### ISSUE TITLE
vm.power -wait flag doesn't appear to wait for shutdown to complete

### ISSUE THREAD

**Issue by nmonday** [vmware/govmomi#1850]
In order for the -wait flag to be truly useful for us, we need the shutdown process to complete before the next part of our script attempts to de-register the VM. This isn't happening.

Here is the snippet of our script that is failing--it immediately tries to deregister the VM as soon as the guest OS shutdown has successfully initiated, not waiting until it completes. We could work around this, but it sure would be nice if we didn't have to. 

```
if [[ $POWERSTATE == "poweredOn" ]]
  then
    echo "Powering off VM in order to migrate it to the new vCenter."
    echo "Attempting graceful shutdown if VMware Tools present; if not, hard power-off."
    govc vm.power -u $SOURCE_VC_URL -s=true -wait=true -force=true "/$DC/vm/$FOLDER_ON_SOURCE/$i"
  fi

  echo "    De-registering $i from $SOURCE_VC"
  govc vm.unregister -u $SOURCE_VC_URL "/$DC/vm/$FOLDER_ON_SOURCE/$i"
```

**Comment by dougm** [comment]
The `-wait` flag is actually `true` by default and was added so that `-wait=false` could be used to disable the code that waits for the power **task** to complete.  In the case of `Shutdown guest`, there is no associated **task** to wait for.  We can add something that waits for the VM **power state** to transition, in the meantime you can use this to wait after calling `vm.power -s`:

```sh
govc object.collect -s "/$DC/vm/$FOLDER_ON_SOURCE/$i" -runtime.powerState poweredOff
```
