### ISSUE TITLE
govc - HostNasVolumeSpec and securityType

### ISSUE THREAD

**Issue by kayshavd** [vmware/govmomi#2084]
The HostNasVolumeSpec  object does support specifying the securityType to be used for NFS datastores. Any reason why govc does not have an option to supply the securityType as an argument?

Or, is there another way to specify the security type after NFS datastore is created?

**Comment by dougm** [comment]
Looking at the git history, I think only because the `datastore.create` command was added before the securityType field was added to the API (in 6.0)

Happy to accept a PR that adds a flag to set the field.  The current fields are set here: https://github.com/vmware/govmomi/blob/609218c5232673cec215d088eb01d043120de385/govc/datastore/create.go#L196
