### ISSUE TITLE
Escaping Object Names

### ISSUE THREAD

**Issue by gsexton** [vmware/govmomi#2101]
I'm trying to troubleshoot a BOSH issue. I've come up with a work-around for the BOSH problem, but now I've run into a funny problem with VSphere (I think). To try to understand what's happening, I was using govc to poke around.

Say I have a network named in the format "a.b.c/mask-bits". For example, "10.11.16/24". 

```bash
$]govc ls /Datacenter/network/10.11.16/24
/Datacenter/network/10.11.16/24 (Network)
```

If I escape the network name it's not returned as expected.

```bash
$]govc ls /Datacenter/network/10.11.16%2f24
(nothing)
```

referencing this page:

https://www.vmware.com/support/orchestrator/doc/vco_vsphere50_api/html/VcDatacenter.html

I would expect it to work. The reason I'm interested in escaping it is because BOSH treats a network name with a / in it as PortGroup/NetworkName.

I'm probably seeing this wrong. If anyone could give me a hand, I would appreciate it.

**Comment by dougm** [comment]
govmomi/govc doesn't unescape object names, nor does the vSphere API. So I think what you're seeing above is the expected behavior currently.  The doc you referenced is VCO, not vSphere.  iirc there is/was a vCenter UI workflow that would escape `/` in object names, but I haven't seen that when using the API directly

Not sure about BOSH, have you opened an issue in that repo?

**Comment by gsexton** [comment]
Thanks. I've opened an issue on vsphere-cpi.
