### ISSUE TITLE
How can I find a specific task using govmomi and wait for it?

### ISSUE THREAD

**Issue by chardch** [vmware/govmomi#2118]
How can I find a specific task, such as importing an OVF by name, and then wait for it? It seems like there are only ways to run  functions on the recent tasks: https://github.com/vmware/govmomi/blob/master/govc/task/recent.go#L164

**Comment by dougm** [comment]
If the task you're looking for is still running, it'll be in the `recentTask` list.

You can also use TaskHistoryCollector, which can also get older tasks: https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.TaskHistoryCollector.html

The govc command uses the `recentTask` field, since it also works directly against ESX hosts. Whereas TaskHistoryCollector requires vCenter.  We could add a higher-level wrapper to govmomi for this, it would look very close to the `EventHistoryCollector` wrapper: https://github.com/vmware/govmomi/blob/master/event/history_collector.go

In either case, once you find the task you're looking for, you can use `object.NewTask(client, ref).Wait()` to wait for the task to complete.

**Comment by toomasp** [comment]
Could you please show some sample code on how to get tasks from vCenter for a host? I cannot seem to figure out the plumbing between the different object types to call on.

**Comment by dougm** [comment]
If you just need the recent tasks for a specific host, something like:
```go
		obj, err := find.NewFinder(c).HostSystem(ctx, "hostname")
		if err != nil {
			return err
		}

		pc := property.DefaultCollector(c)

		var host mo.HostSystem
		err = pc.RetrieveOne(ctx, obj.Reference(), []string{"recentTask"}, &host)
		if err != nil {
			return err
		}

		var tasks []mo.Task
		err = pc.Retrieve(ctx, host.RecentTask, nil, &tasks)
		if err != nil {
			return err
		}
```
