### ISSUE TITLE
Proposal: Re-authenticate on NotAuthenticated error

### ISSUE THREAD

**Issue by hickeng** [vmware/govmomi#224]
Eventually an authenticated connection times out and any attempt to use it causes authentication errors.
Add a reauthenticate hook and have that called by any failing method so that an attempt can be made to reauthenticate before failing the operation prompting the error. This could use cached credentials or a long term session token.

**Comment by pietern** [comment]
We now have keepalive functionality: 
https://github.com/vmware/govmomi/blob/v0.1.0/session/keep_alive.go

This wraps a soap.RoundTripper and waits for idle time to pass before sending a no-op request to keep the session alive. The idle timer starts when a login operation returns successfully and stops when a logout operation returns successfully.

In a similar fashion, a wrapper could be created that catches a NotAuthenticated error and (re-)authenticates the session. This is more tedious however, because a user with non-administrator privileges can receive a NotAuthenticated fault for some operations and not for others. Keepalive bypasses this issue.

**Comment by lox** [comment]
Any guidance on how to actually use that round tripper @pietern?
