### ISSUE TITLE
collector.WaitForUpdates does not take waitOptions as an arg

### ISSUE THREAD

**Issue by mridulganga** [vmware/govmomi#2241]
I see there are multiple functions called WaitForUpdates
- first one belongs to the github.com/vmware/govmomi/property package
- second one is a struct method in the same package.

The first method does not allow giving version as an input, but it has Wait Filters as an available option.
In the 2nd method - we have version as an input but it is missing the Wait Filters as an argument.

1st method -
`func WaitForUpdates(ctx context.Context, c *Collector, filter *WaitFilter, f func([]types.ObjectUpdate) bool) error`

2nd method - 
`func (p *Collector) WaitForUpdates(ctx context.Context, v string) (*types.UpdateSet, error) `

Can we please allow wait filters in the 2nd method as well ?
I see that the change is very simple enough and I am not sure why its missing.

**Comment by dougm** [comment]
The 1st one creates a new PropertyCollector instance to wait for the updates and it handles the versioning internally.
The 2nd one uses the session's PropertyCollector singleton, and you can only have 1 active wait against the singleton, so I don't think it gets used often. (We should document that). Still, we could add the `*WaitOptions` param as you suggest.

In the meantime, you can also call the generated code directly just as the 2nd method itself does:
https://github.com/vmware/govmomi/blob/50c576d6470e7ab9803ceb466ac34f936971dfc1/property/collector.go#L101-L111

Just need to use a `*vim25.Client` instead of `p.roundTripper`

**Comment by embano1** [comment]
@mridulganga can we close this issue then?

**Comment by mridulganga** [comment]
Yes,
We can close this. Sorry I didn't know I was supposed to close it.
Thanks for the help.
