### ISSUE TITLE
esxi host to portgroup (-name) assignment

### ISSUE THREAD

**Issue by explimpl** [vmware/govmomi#2290]
Hello,

i want to find out which dvs portgroups are available for specific ESXi Hosts managed by a vCenter,
The result should look like this:
esxihost1 -> portgroupname1
esxihost1 -> portgroupname2
esxihost2 -> portgroupname1
esxihost2 -> portgroupname3

I tried to implement it with the govc command dvs.portgroup.info / host.info (-json) but i could not find the portgroup name, just portgroup keys. is there a command to see which name belongs to which portgroup key? it is just about to have a list of host to portgroup (-name) assignment.

Thank you in advance.

**Comment by dougm** [comment]
You can use the `ls` command like so:
```console
% govc ls -t DistributedVirtualPortgroup 'host/*/*'
```

Or `object.collect` of the host `network` property:
```bash
for host in $(govc find / -type h); do
  networks=$(govc object.collect -s -d " " "$host" network)
  echo "$host:"
  for network in $networks; do
    path=$(govc ls -L "$network")
    echo "  $path"
  done
done
```

**Comment by explimpl** [comment]
Thank you Doug! That helps..just wondering why the second method (object.collect) does not show the portgroup-name, just "dvportgroup-xyz".

**Comment by dougm** [comment]
The first param given to `object.collect` is `"$host"`, which is a [HostSystem](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.HostSystem.html#field_detail) object.  The second param is `network`, which is a field of the HostSystem and the linked doc on the network field:
> A collection of references to the subset of network objects in the datacenter that are available in this HostSystem. 

In other words, the host object refers to networks by ID rather than NAME.  You can also use object.collect to get the network name, changing the script like so:
```bash
#!/bin/bash

for host in $(govc find / -type h); do
  networks=$(govc object.collect -s -d " " "$host" network)
  echo "$host:"
  for network in $networks; do
    name=$(govc object.collect -s "$network" name)
    echo "  $name"
  done
done
```

**Comment by explimpl** [comment]
Thanks a lot Doug! Seems so that you can fetch nearly any information usually needed by just using govc. no need to use a scripting/programming language for many use cases.
