### ISSUE TITLE
govc disk.register behaves differently in vSphere 7.0 as compared to vSphere 6.7U3

### ISSUE THREAD

**Issue by gchakravarthi** [vmware/govmomi#2352]
On a vSphere 6.7U3 setup, when `govc disk.register` is performed on a copy of an already promoted vmdk as FCD (i.e., copy is present in a different directory on the datastore as part of the restore from backup), it returns a different FCD UUID as compared to its original copy. Whereas on vSphere 7.0, the same action results in returning the same FCD UUID.

- Since the version of govmomi (0.21.1) is the same, is this change in behavior expected? If so, what is the reason for the same?
- Is there an alternate API which could be used to get the same behavior seen on vSphere 6.7U3, on vSphere 7.0 ?
	
Given below are the steps followed and the corresponding outputs, for reference. The datastore is a NFS datastore, and the govmomi version is 0.21.1

_Behavior on 6.7U3_
```
$ govc datastore.mkdir disks
$ govc datastore.disk.create -size 1G disks/disk1.vmdk
[01-04-21 21:25:53] Creating [ds] disks/disk1.vmdk...OK
$ govc disk.register disks/disk1.vmdk
0c012739-1abc-4b1b-94fb-4e501605dbf4 <== FCD UUID of the original disk

$ govc datastore.mkdir disks_copy

(on the datastore, copy the contents of disks directory inside disks_copy directory)

$ govc disk.register disks_copy/disk1.vmdk
25d75b41-dd48-481d-8c56-574186398e38 <== FCD UUID of the copied disk. It is different form the above original disk.
$ govc disk.ls -L <== This lists both the registered disks (original and copy)
25d75b41-dd48-481d-8c56-574186398e38  [ds] disks_copy/disk1.vmdk
0c012739-1abc-4b1b-94fb-4e501605dbf4  [ds] disks/disk1.vmdk

```
_Behavior on 7.0_
```
$ govc datastore.mkdir disks
$ govc datastore.disk.create -size 1G disks/disk1.vmdk
[01-04-21 22:29:34] Creating [ds] disks/disk1.vmdk...OK
$ govc disk.register disks/disk1.vmdk
b4fe5918-5dbb-42ea-aaf9-cefdd005b539 <== FCD UUID of the original disk

$ govc datastore.mkdir disks_copy

(on the datastore, copy the contents of disks directory inside disks_copy directory)

$ govc disk.register disks_copy/disk1.vmdk
b4fe5918-5dbb-42ea-aaf9-cefdd005b539 <== FCD UUID of the copied disk. It is exactly same as the above original disk.
$ govc disk.ls -L <== This lists only the original disk and NOT the copied disk
b4fe5918-5dbb-42ea-aaf9-cefdd005b539  [ds] disks/disk1.vmdk
```

**Comment by dougm** [comment]
We haven't changed anything related on the client side in govmomi or govc.  Can you share the `govc about` for 7.0?

cc @dsu-igeek @divyenpatel who may have some pointers

**Comment by divyenpatel** [comment]
@bandyopadhyays-vmware can help with this query.

**Comment by bandyopadhyays-vmware** [comment]
RegisterDisk() design have changed considerably from 6.7U3 to 7.0.
Some new features added:

1. In 6.7U3 , if a disk was attached to a VM (means VM knows about this disk already) then registerDisk() was not supported operation. We added that support in 7.0 onwards.
2. Due to above error handling have changed significantly in 7.0

RegsiterDisk() was designed to promote a virtual disk to a First Class Disk; A virtual disk was not supposed to have a UUID associated with it. So, if we find a UUID with such a disk in 7.0, first we check if that UUID is in use, if it is in use then we create a new one (otherwise there could be a duplicate UUID in the cluster which is going to be bad). 

That's why you may see some differences between 6.7U3 and 7.0.
BTW, in all other good cases, 7.0 will still allow to re-use the UUID whenever possible (e.g. there is no duplication).

one typical use case is correct backup and restore process: backup may be done on a folder and one may restore it in another folder duplicating the UUID (if a buggy backup program doesn't delete the old stuff before restoring)..we can't allow that to happen. So, these changes were necessary.

thanks, Som.

**Comment by gchakravarthi** [comment]
Hi Som
Thanks for the clarifications. I have a few questions in this regard.

> first we check if that UUID is in use, if it is in use then we create a new one (otherwise there could be a duplicate UUID in the cluster which is going to be bad).

- In the above reproduction of the issue using `govc register`, why is it not creating a new one? How is "in use" figured out?
- In the example you have mentioned, are you referring to the disk UUID or the FCD UUID when you say UUID?
- Which API should be used promote a disk from a backup as FCD, with a new FCD UUID?

Thanks
Ghanashyam

**Comment by bandyopadhyays-vmware** [comment]
1) I was referring to FCD UUID in this case
2) We have stored FCD UUID in internal config files in datastore.
3) We figure out internally if the FCD being registered having the same UUID : If not used then it gets the same UUID, if used it gets a new UUID. 
4) You can call another API called retrieveVStorageObject() to figure out if the FCD UUID is in use or not.

thanks, Som.
