### ISSUE TITLE
govc version says 0.0.0

### ISSUE THREAD

**Issue by zibboehmert** [vmware/govmomi#2401]
After updating from 0.24.0 to 0.25.0 using
```
$ govc version
govc 0.24.0
$ go get -u github.com/vmware/govmomi/govc
$ govc version
govc 0.0.0
```
`govc version` does not work anymore. Everything else used so far seems to work.
I am on Fedora 32.
```
$ go version
go version go1.14.15 linux/amd64
```
Please let me know if you need more information, and which.

**Comment by embano1** [comment]
Thank you @zibboehmert We did a release pipeline overhaul with 0.25.0 to provide pre-built binaries and detailed release information in the binaries, incl. commits. 

Details here: https://github.com/vmware/govmomi/blob/master/govc/README.md

You can (programmatically) pull a release artifact for your platform here: https://github.com/vmware/govmomi/releases/tag/v0.25.0

**Comment by dougm** [comment]
@embano1 can folks run make or goreleaser locally to produce a govc binary with version/commit info injected?

**Comment by embano1** [comment]
> @embano1 can folks run make or goreleaser locally to produce a govc binary with version/commit info injected?

Absolutely! Will file a documentation update for this.

**Comment by zibboehmert** [comment]
Thank you @embano1! So everything else should work as expected, or better use one of the artifacts?

**Comment by embano1** [comment]
There's no difference in the actual code, only that the build variables are not set when you pull via `go get`.
Not sure about your use case, but if you only need a `govc/vcsim` artifact to do your work, it's probably a good idea to use the artifacts or container images we produce since v0.25.0.

**Comment by jhg03a** [comment]
This appears to still be using 0.0.0.0 when installed via brew which uses the release artifacts.

**Comment by dougm** [comment]
@jhg03a looks like this is a homebrew issue, they are building from source, rather than using the release binary:
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/g/govc.rb#L29

Our [release binaries](https://github.com/vmware/govmomi/releases) are built by 'goreleaser', which uses ldflags to inject the version, as the original script did: https://github.com/vmware/govmomi/blob/c1d08321559980694a4e2b3b40693cb04aef38f5/govc/build.sh#L17

Example:
```console
% go build -ldflags="-w -X github.com/vmware/govmomi/govc/flags.BuildVersion=v0.12.3" .
% ./govc version
govc 0.12.3
```

Do you want want to raise an issue in the homebrew repo?
