### ISSUE TITLE
Register / Unregister vm

### ISSUE THREAD

**Issue by packetq** [vmware/govmomi#2501]
Hi,

I'm trying to figure out how to register/unregister an existing vm. Are there any examples of this? I looked at the cli code, but I'm not really following what is happening there. I also looked at the source, but i'm not sure how to setup the call the folder api for the register. 

Thanks.

**Comment by embano1** [comment]
There's multiple ways to get there, but an easy way is via the `finder`.

Create a finder from your client: https://pkg.go.dev/github.com/vmware/govmomi/find#NewFinder 

Then you can use the finder instance to access your datacenter, retrieve its folders, etc. Since many commands are using the ManagedObjectReference, you can easily retrieve them via their `object.Reference()` methods.

Finder can also be used to directly search for a folder. API details here: https://vdc-download.vmware.com/vmwb-repository/dcr-public/723e7f8b-4f21-448b-a830-5f22fd931b01/5a8257bd-7f41-4423-9a73-03307535bd42/doc/vim.Folder.html

**Comment by packetq** [comment]
Hi,

Thanks for the reply. I got a little further, but I'm having trouble with the resource pool arg to folder.RegisterVM. I don't have vms in a resource pool. I tried passing nil, but I get an error about a missing parameter. Is there some way to default this? I tried the ResourcePoolOrDefault function with an empty string, but I get "default resource pool resolves to multiple instances, please specify". Any advice would be much appreciated.

Thanks.

**Comment by packetq** [comment]
Hi,

Ok. I figured it out. You can grab the pool from the HostSystem object via the Host.ResourcePool function. Thanks again for putting me on the right track.

Thanks.
