### ISSUE TITLE
[BUG] Name not sanitised when using govc's library.deploy.

### ISSUE THREAD

**Issue by eraserpencil** [vmware/govmomi#2505]
Names of VMs are not sanitised when deployed, I had a VM with the name "-options=ubuntu.json". Maybe it's a feature, but the docs should reflect so.

**To Reproduce**

1.  `./govc library.import "Library_name" https://cloud-images.ubuntu.com/releases/bionic/release-20210623/ubuntu-18.04-server-cloudimg-amd64.ova`
2. `./govc library.deploy /Library_name/ubuntu-18.04-server-cloudimg-amd64 -options=ubuntu.json ubuntu18`

**Expected behavior**
A VM by the name of "ubuntu18" to be created and no VMs by the name "-options=ubuntu.json" to be created.

**Affected version**
Running vSphere6.7, API version 6.7.3

**Additional context**
The contents of `ubuntu.json` should not be relevant, but they were generated by 
`govc import.spec ~/Downloads/ubuntu-18.04-server-cloudimg-amd64.ova | python -m json.tool > ubuntu.json` on the image i downloaded locally.

**Comment by dougm** [comment]
This is due to Go's flag parser and not unique to the library.deploy command, it's come up a number of times before and we should add some doc at least other than the 'Examples' help section.  You just need to specify any `-flag-name=value` before the non-flag arguments.  In this case:

`./govc library.deploy -options=ubuntu.json /Library_name/ubuntu-18.04-server-cloudimg-amd64 ubuntu18`
