### ISSUE TITLE
[BUG] Finder returns duplicate refs for same object

### ISSUE THREAD

**Issue by embano1** [vmware/govmomi#2561]
When this finder method is called, e.g. internally by `govc`, with an object name without type/prefix
Example: `govc fields.set TemplateName foobar test-vm-1` instead of `fields.set TemplateName foobar vm/test-vm-1` returns the same element twice (different paths) instead of just one element leading to unneccesary RPCs.

https://github.com/vmware/govmomi/blob/aa754c9cd32617daaed5dcab8646feb14e60f2ad/find/finder.go#L263-L286

Related: #2556

**Comment by embano1** [comment]
@dougm a naive approach would be de-duping the returned list, but I'm sure you have a better idea :)

**Comment by dougm** [comment]
This issue is specific to the `ManagedObjectList` method. The finder methods for specific types (e.g. VirtualMachineList) limit the search to the type's folder already (vm,host,datastore,network)

Example from #2556 , with an input path of just the entity name `test-vm:03:12Z`, two paths are returned:
`/vcqaDC/vm/test-vm:03:12Z` and `/vcqaDC/host/cls/10.78.209.130/test-vm:03:12Z`

Workaround would be to specify full path `/vcqaDC/vm/test-vm:03:12Z` or relative to DC `vm/test-vm:03:12Z`

Since `ManagedObjectList` doesn't know what type its looking for, when given just a name it will traverse all folders and in this case the 2nd is returned via [HostSystem.vm](https://github.com/vmware/govmomi/blob/aa754c9cd32617daaed5dcab8646feb14e60f2ad/list/lister.go#L444) property traversal.

We could de-dup, but the only way to avoid traversing the entire inventory tree would be to specify a path, rather than just a name.  Tempted to add something like the patch below.

```diff
modified   govc/flags/datacenter.go
@@ -203,6 +203,9 @@ func (flag *DatacenterFlag) ManagedObjects(ctx context.Context, args []string) (
 			refs = append(refs, ref)
 			continue
 		}
+		if !strings.Contains(arg, "/") {
+			return nil, fmt.Errorf("%q must be qualified with a path", arg)
+		}
 		elements, err := finder.ManagedObjectList(ctx, arg)
 		if err != nil {
 			return nil, err
```

**Comment by dougm** [comment]
btw, all the commands that use `DatacenterFlag.ManagedObjects` used to require a path rather than just name as the input arg prior to #689 .  Examples for the commands also use path input rather than just name.

**Comment by embano1** [comment]
I wasn't aware that not specifying a relative/absolute path is considered incorrect and just happens to work because we did not put guardrails around it. Instead of adding more logic around filtering I agree we should err out as proposed. Will file PR.
