### ISSUE TITLE
vm.clone -force flag not working

### ISSUE THREAD

**Issue by Crono1981** [vmware/govmomi#2707]
**Describe the bug**
On running vm.clone command with -force flag, if an existing vm exists with the same name, I get a message saying that there's already an existing vm with that name.

**To Reproduce**

1. Run vm.clone with any template as a source and any name, with -force flag
2. Run the exact same command again

**Expected behavior**
The -force flag should make the second command run overwrite the previously cloned vm

**Affected version**
0.27.2

**Additional context**
I'm actually trying to copy a template as another template, so I'm using both -force and -template flags.

**Comment by dougm** [comment]
What is the exact error message?  `-force` only bypasses govc's own check, where the message would be:

```
file ${vm_name}/${vm_name}.vmx already exists
```
https://github.com/vmware/govmomi/blob/70b89df8d1dac65eb695386617abccc20badcc8e/govc/vm/clone.go#L444

**Comment by embano1** [comment]
@dougm from reading the help string

`Create VM if vmx already exists `

I would expect govc to also handle vCenter errors due to existing VM.

**Comment by dougm** [comment]
> I would expect govc to also handle vCenter errors in case of existing VM.

iirc vCenter doesn't require the VM name to be unique and will append to the name "foo", "foo (1)", "foo (2)".  We added this vmx check to avoid this and `-force` to allow it.
That's why I asking what the exact error message is, since I've not seen vCenter error due to VM having the same name before.
Better yet output with `-trace` so we can see the Fault structure.
