### ISSUE TITLE
any way to limit json output on govc host.info?

### ISSUE THREAD

**Issue by charliedrage** [vmware/govmomi#277]
I'm using govc in a simple bash script to deploy a scalable cluster of things. 

Is there any way to limit the amount of output / certain details when using:
```bash
govc host.info -json=true /DC4/host/cloud.ca/esx0.cloud.ca 
```

If not, that's okay! I can build a small go script using govmomi instead.

Many thanks,

**Comment by pietern** [comment]
We don't have an option to limit the output. I agree some commands do return a *ton* of data, but we've typically resorted to filtering that data by piping it to [jq](http://stedolan.github.io/jq/). This has proven very useful and so much so that there hasn't been a need to ask vSphere to return less data.

Good luck!
