### ISSUE TITLE
[BUG] Cannot read maxMtu on a dvs

### ISSUE THREAD

**Issue by hxul** [vmware/govmomi#2796]
**Describe the bug**
My project requires reading maxMtu setting of a DVS.  It is impossible to read as this setting resides in VMwareDVSConfigInfo which cannot be converted from BaseDVSConfigInfo because VMwareDVSConfigInfo type missed implementing the interface GetDVSConfigInfo

**To Reproduce**
my piece of test code:

	var dvpgmo mo.DistributedVirtualPortgroup
	var dvsmo mo.VmwareDistributedVirtualSwitch
	var vmwDvsConfigInfo *types.VMwareDVSConfigInfo
	if network.Reference().Type == "DistributedVirtualPortgroup" {
		dvpg := *network.(*object.DistributedVirtualPortgroup)
		err := dvpg.Properties(ctx, dvpg.Reference(), []string{"key", "config.distributedVirtualSwitch"}, &dvpgmo)
		if err != nil {
			fmt.Println("failed to find dvpg mo", err)
			return
		}
		if dvpgmo.Config.DistributedVirtualSwitch == nil {
			fmt.Println(err)
			return
		}
		err = dvpg.Properties(ctx, *dvpgmo.Config.DistributedVirtualSwitch, []string{"uuid", "config"}, &dvsmo)
		if err != nil {
			fmt.Println("failed to find dvs mo", err)
			return
		}

		fmt.Println("dvsmo: ", dvsmo.Config.GetDVSConfigInfo().Uuid)
		// need a fix in vim25/types/if.go
		// 2746 func (b *VMwareDVSConfigInfo) GetDVSConfigInfo() *VMwareDVSConfigInfo {
		// 2747 <---return b
		// 2748 }
		vmwDvsConfigInfo = (dvsmo.Config).(*types.VMwareDVSConfigInfo)  //this statement will return error in compilation without the about interface implemenationin the comments
		fmt.Println("mtu:", (*vmwDvsConfigInfo).MaxMtu)

**Expected behavior**
we should be able to get VMwareDVSConfigInfo object in some way to get its specific properties.

**Affected version**
latest

**Screenshots/Debug Output**
If applicable, add screenshots or debug output to help explain your problem.

**Additional context**

**Comment by dougm** [comment]
The `Base` interfaces in govmomi are only generated for types extended by other types.  In this case [DVSConfigInfo](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.DistributedVirtualSwitch.ConfigInfo.html) is extended by [VMwareDVSConfigInfo](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.dvs.VmwareDistributedVirtualSwitch.ConfigInfo.html).  Since no other types extend `VMwareDVSConfigInfo`, you just need to use the type directly to access its specific fields.  Here's an example:
```go
		finder := find.NewFinder(c)
		networks, err := finder.NetworkList(ctx, "*")
		if err != nil {
			return err
		}

		for _, network := range networks {
			obj, ok := network.(*object.DistributedVirtualPortgroup)
			if !ok {
				continue
			}

			var dvpg mo.DistributedVirtualPortgroup
			var dvs mo.DistributedVirtualSwitch

			err := obj.Properties(ctx, obj.Reference(), []string{"key", "config.distributedVirtualSwitch"}, &dvpg)
			if err != nil {
				return err
			}

			err = obj.Properties(ctx, *dvpg.Config.DistributedVirtualSwitch, []string{"uuid", "config"}, &dvs)
			if err != nil {
				return err
			}

			info := dvs.Config.(*types.VMwareDVSConfigInfo)
			fmt.Printf("%s mtu=%d\n", info.Uuid, info.MaxMtu)
		}
```
