### ISSUE TITLE
govc import.ova doesn't provide vApp properties

### ISSUE THREAD

**Issue by iNode** [vmware/govmomi#288]
govc import.ova doesn't provide the way to specify vApp properties for VM.

**Comment by bruceadowns** [comment]
To fill out the feature set of govc, you may want a way to view ovf parameters of a given ovf/ova file, and then subsequently provide the parameters.

ovftool displays the ovf parameters in probe mode (i.e. ovftool va.ovf) and provides a --prop argument to specify the desired (hidden or otherwise) settings during deployment. The powercli has its equivalents in the Get-OvfConfiguration cmdlet and the –OvfConfiguration parameter.

For setting required ovf parameters in govc, it may be a matter of adding a reasonable multi-valued argument to govc import.ov{f,a} and propagate them into OvfCreateImportSpecParams::PropertyMapping around govc/importx/ovf.go#L135-L140.

**Comment by bruceadowns** [comment]
To achieve parity with ovftool (not necessarily the goal), the following options (non-exhaustive list) are needed for govc import.ovf:

* deployment option (small, medium, ...)
* disk mode (thin, thick, ...)
* folder
* network
* accept eula
* validate signature
* overwrite (existing)
* ip allocation policy (dhcp, static, ...)
* power on
* ovf property (-prop:"key"="value")
* wait for ip

**Comment by bruceadowns** [comment]
In an attempt to distill to only the immediately necessary options of -power-on, -prop, and -wait-for-ip, here is a cli proposal:

    $ govc import.ovf --help
    Usage: govc import.ovf [OPTIONS] PATH_TO_OVF
    
    Options:
      -dc=                                       Datacenter [GOVC_DATACENTER]
      -debug=true                                Store debug logs [GOVC_DEBUG]
      -ds=LUN221                                 Datastore [GOVC_DATASTORE]
      -host=                                     Host system [GOVC_HOST]
      -host.dns=                                 Find host by FQDN
      -host.ip=                                  Find host by IP address
      -host.ipath=                               Find host by inventory path
      -host.uuid=                                Find host by instance UUID
      -json=false                                Enable JSON output
      -k=true                                    Skip verification of server certificate [GOVC_INSECURE]
      -persist-session=true                      Persist session to disk [GOVC_PERSIST_SESSION]
      -pool=                                     Resource pool [GOVC_RESOURCE_POOL]
      -power-on=false                            Power On VM
      -prop=key:value                            OVF key-value property
      -u=https://@platsec-vc.eng.vmware.com/sdk  ESX or vCenter URL [GOVC_URL]
      -wait-for-ip=false                         Wait for VM IP Address
