### ISSUE TITLE
[BUG] `object.Datastore.NewURL()` uses the wrong field for dsName query

### ISSUE THREAD

**Issue by Eifoen** [vmware/govmomi#3267]
**Describe the bug**
The `Datastore.NewURL()` function composes a `url.URL` to get a file via the `/folder` endpoint. This endpoint requires the `dsName` query parameter to be set to the name of the datastore. In the current implementation the function `d.Name()` is used to fill this parameter. However, this function is embedded from `Common.Name()` and does not return the real name of the datastore. Instead it returns its inventory path or "" most of the time.

**To Reproduce**
Use the `Datastore.NewURL()` function to generate a download URL

**Expected behavior**
Instead of `d.Name()` the function should use `d.ObjectName(context.Context)` which receives the real name of the datastore from the VSX/ESX itself.

**Affected version**
<= v.0.32

**Additional context**
The solution poses a problem, since the  `d.ObjectName(context.Context)` call does require a context for the request scope. This is very unfortunate, but the current implementation is pretty useless anyways (and might not be used, otherwise this must have come up earlier.)

I would prepare a PR to fix this, if my proposed fix is okay for you (or another solution of course)
Cheers

**Comment by dougm** [comment]
Hi @Eifoen , indeed this is an issue if the object.Datastore instance is created by something other than the Finder, since both `InventoryPath` and `DatacenterPath` can be empty. Can you describe how object.Datastore is created in your case?

When created by Finder, `Common.Name()` should always be the same as `ObjectName()`, since Common.Name is `path.Base(c.InventoryPath)` and InventoryPath is composed using each object's `name` property. Can you provide an example when they are different?

**Comment by dougm** [comment]
Thanks @Eifoen , makes sense. Are you calling `NewURL()` directly or indirectly via Datastore.{Upload,Download} ?
Did your workaround also include setting `Datastore.DatacenterPath` ?
If you could review #3277 , we can adjust as needed.
