### ISSUE TITLE
govc resolves multiple datastores when exact name given?

### ISSUE THREAD

**Issue by ringods** [vmware/govmomi#346]
When trying to create a directory in one of my datastores, I get this:

```
$ govc ls /ha-datacenter/datastore/
/ha-datacenter/datastore/datastore1
/ha-datacenter/datastore/ProductionServers
/ha-datacenter/datastore/Software
$ govc datastore.mkdir /ha-datacenter/datastore/ProductionServers/cloud-init/
Error: default datastore resolves to multiple instances, please specify
```

How come govc reports it can resolve multiple instances?

govc v0.2.0, darwin_amd64

**Comment by ringods** [comment]
Same for `datastore.cp`:

```
$ govc datastore.cp configdrive.iso /ha-datacenter/datastore/ProductionServers/cloud-init/
Error: default datastore resolves to multiple instances, please specify
```

**Comment by pietern** [comment]
The problem here is that the `ls` command lists the tree structure of the virtual infrastructure, whereas `datastore.{ls,mkdir,...}` use the tree structure starting at the datastore root. This means that the command can't be used in the way you specify, but has to be used like this:

```
govc datastore.ls -ds=ProductionServers .
govc datastore.mkdir -ds=ProductionServers ./cloud-init
```

The way you tried to use it is interesting. The reason why implementing this is tricky is that we would need to differentiate between virtual infrastructure paths and datastore paths. It's not possible to tell whether or not `/ha-datacenter/datastore/datastore1/foo` refers to the `foo` directory, or to the whole path on the default datastore.
