### ISSUE TITLE
object/search_index.go/FindChild returning <nil>, <nil> on error

### ISSUE THREAD

**Issue by BenPhegan** [vmware/govmomi#350]
Hi,

After tracking down an issue with http://github.com/rakutentech/terraform-provider-vsphere I came across this code:

https://github.com/vmware/govmomi/blob/master/object/search_index.go#L75

Where on failure to get a valid response returns a `<nil>,<nil>`:

```go

	if res.Returnval == nil {
		return nil, nil
	}
```

Most code using the library that I have seen will guard this with a call similar to this:

```go

	res, err := methods.FindChild(ctx, s.c, &req)
	if err != nil {
		return nil, err
	}
```

Basically instead of being able to gracefully handle the error, this results in a panic, as generally the next thing someone will try and do is use the return value.

Is this by design?  If so, why?  Is there not a better way of responding with a valid error message?  As I am not sure the intent or approach here, I wanted to start a discussion rather than attempting a pull request around this.

Thanks,

Ben

**Comment by dougm** [comment]
It is by design as we following the behavior of the SDK we are wrapping.  From the docs at http://pubs.vmware.com/vsphere-55/topic/com.vmware.wssdk.apiref.doc/vim.SearchIndex.html
"The managed entity that is found, or null if no match is found."

It is up to the caller to decide how to handle an empty search result, which is not an error as far as the API is concerned.
