### ISSUE TITLE
Support for datastore cluster

### ISSUE THREAD

**Issue by kc11381** [vmware/govmomi#386]
Hi,

To support datastore cluster:

Should we have something:
https://github.com/vmware/govmomi/blob/master/find/finder.go look at line number 255.
if ref.Type == "Datastore" || ref.Type == "StoragePod"{

It will give us the both the datastore and datastore cluster and may be we can again reiterate over datastore clusters to get datastores inside them.
Thank you.

**Comment by pietern** [comment]
Thanks for the request. I'm working on this.

**Comment by kc11381** [comment]
@pietern 

If I select a datastore from a esxi host, can I know to which datastore cluster it belongs?
Do we have something like this available?

**Comment by pietern** [comment]
@kc11381 We don't have a facility for that in govc. What you can do, however, is use the JSON output for `govc ls` to get the full object for the datastore cluster. This will have a `ChildEntity` field with references to its datastores.

On the case of this issue: it's not as simple as pointing VM creation to a datastore cluster. It actually needs to go into the storage resource manager and get a recommendation for a datastore and then use that. I'm building that into govc now, but supporting that in terraform will be a separate issue (since it doesn't use govc directly AFAIK).

**Comment by pietern** [comment]
See #428.

The finder now supports going into StoragePod types, which in turn allows `govc ls` to list the datastores inside a datastore cluster. The PR is not done yet and will only be merged after support for creating VMs in a datastore cluster is done.
