### ISSUE TITLE
govc datastore.download/datastore.upload

### ISSUE THREAD

**Issue by groob** [vmware/govmomi#424]
```
[25-01-16 17:32:05] Downloading... OK
govc: ServerFaultCode: A specified parameter was not correct.
url
```
I get the above error when using `govc` with a 5.1 datastore. 
It appears that `ds.DownloadFile(context.TODO(), args[0], args[1], &p)` in datastore/download.go and `ds.UploadFile(context.TODO(), args[0], args[1], &p)` in datastore/upload.go don't work with 5.1 datastores. 

I'll be submitting a pull request that resolves the issue shortly.

**Comment by djoulz22** [comment]
Hi,
+1 with with ESX 5.0.0
With govc V0.2.0, it works perfectly

**Comment by dougm** [comment]
I did a quick test against 5.1, it is caused by our use of a service ticket.  Not sure why, since the method was added in 5.0.  Didn't want to add a version check for this just yet, so added a workaround where you use an env var: `GOVMOMI_USE_SERVICE_TICKET=false`
You can also use that within the GOVC_URL as a query param.  We can revisit if the workaround too much hassle.

Closing this and #425 for now.
