### ISSUE TITLE
finder.DatastoreList broken with Datastore Clusters / Storage Pods

### ISSUE THREAD

**Issue by brandonweeks** [vmware/govmomi#540]
When running a simple govmomi program against a vSphere 6.0 U2 server, `finder.DatastoreList` fails with a `datastore '*' not found` error. However `finder.DatastoreClusterList` returns the two clusters as expected.

**Comment by dougm** [comment]
This is another case where the Finder is not recursing, "*/*" would work I believe.  Planning to fix this as we have similar cases for finding objects within folders (StoragePod extends Folder).

**Comment by xrix4096** [comment]
Is this because of Datacenter.Folders() returning the wrong InventoryPath for each of the folders if the datacenter is not at root? The InventoryPath is always set to "/" + "datacentername" + vm/network/whatever. The actual inventory path needs to have the parent info prepended rather than assuming it is at "/"

**Comment by Hedda** [comment]
@dougm  FYI; I can confirm that listing datastores in SDRS (Storage DRS) clusters still do not work.

Had to remove datastore from the SDRS (Storage DRS) cluster before govmomi or govc can list it.

Tested this also with govc packaged with VIC (vSphere Integrated Containers) v0.6.0 alpha release.

This issue means that VIC (vSphere Integrated Containers) currently do not support SDRS clusters.

We are using vCenter Server version 6.0.0.20000
