### ISSUE TITLE
Get uuid of VSAN datastore object by name

### ISSUE THREAD

**Issue by abrarshivani** [vmware/govmomi#541]
How can I get uuid of VSAN datastore object by name or vice versa? For example, I have [vsanDatastore] volumes/test.vmdk and I need [vsanDatastore] 59427457-6c5a-a917-7997-0200103eedbc/test.vmdk where '59427457-6c5a-a917-7997-0200103eedbc' is uuid of volumes.

**Comment by dougm** [comment]
Not sure, there is http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.DatastoreNamespaceManager.html

But it only provides Create (see example below) and Delete methods, no query.

Any ideas @fdawg4l @cormachogan ?

```
% govc datastore.mkdir -namespace volumes
/vmfs/volumes/vsan:52f4755012777dcf-398a703900bb154a/b6188957-7346-cf6c-72fa-000c29e09dc1
% date > date.txt
% govc datastore.upload date.txt volumes/date.txt >/dev/null
% govc datastore.ls b6188957-7346-cf6c-72fa-000c29e09dc1
date.txt
% govc datastore.ls volumes
date.txt
```

**Comment by fdawg4l** [comment]
I could not find a programmatic way to get the UUID of a dirent on a VSAN datastore.

**Comment by cormachogan** [comment]
Let me ask some folks...

**Comment by fdawg4l** [comment]
@cormachogan Can you initiate that discussion with the relevant folks and include me?  I hunted high and low and couldn't find anything in the public api but it's very likely I missed it.  Moreover, since the UUID semantic really seems to only be exposed via the `DatastoreNameSpaceManager` (which returns a `vmfs` path which happens to include the UUID), I'm wondering if we should be using the names of objects rather than UUIDs otherwise it wouldn't be so hidden in the API.  

I'm just speculating.  Any help would be greatly appreciated.

**Comment by abrarshivani** [comment]
I found an api that convert namespace path to uuid path but it doesn't work. Also, it is not documented anywhere.
<img width="959" alt="screen shot 2016-07-19 at 4 20 08 pm" src="https://cloud.githubusercontent.com/assets/1269660/16969881/05c21750-4dcd-11e6-91d3-098bbd03c465.png">

**Comment by dougm** [comment]
Any luck with this @abrarshivani ?

**Comment by abrarshivani** [comment]
@dougm No luck with this. Just found work-around.

**Comment by dougm** [comment]
ok, closing for now then.
