### ISSUE TITLE
Is there a way to export a VM to ovf/ova with govc?

### ISSUE THREAD

**Issue by weinrea** [vmware/govmomi#692]

**Comment by dougm** [comment]
There isn't currently.  I believe the VirtualMachine.ExportVm method would be involved here at least, but haven't looked at it too close yet.

@frapposelli mentioned interested in this too.

**Comment by adtrsa** [comment]
Also am interested in this.  Already using govc to bypass vSphere Web Client where possible (e.g. scripted VM cluster stop/start etc.).  Exporting VM to OVF from vSphere Web Client requires the client integration plugin, which unfortunately does not work on Linux OS (thanks for Flash mess).

**Comment by weinrea** [comment]
@adtrsa you still don't have to use the web client.  use ovftool for exporting VMs on linux.

**Comment by adtrsa** [comment]
@weinrea Thanks for the info, much appreciated.  Will take a look ovftool

**Comment by SudarshanSudie** [comment]
Any place to lookup examples or skeleton code for VirtualMachine.ExportVm method ? Looking at pyvmomi vm export example but not much success. Any guidance on how to go about ExportVm call ?

**Comment by dougm** [comment]
I had started on this as part of the ovf+nfc refactoring done in #805 , but it could use more testing + likely missing features of ovftool's export (which I have yet to look at myself).  The current code is in PR #813 , would be great to get some review on that.

**Comment by SudarshanSudie** [comment]
@dougm - vm.export doesnt seem to get registered , is there a sequence of steps to be followed when I am doing this ? because when I try to run the gov vm.export command , it doesnt seem to recognize it and where are you taking the destination location parameter ?

**Comment by dougm** [comment]
How did you fetch the PR code and build govc?

There are a few ways, you can do the following for example (https://help.github.com/articles/checking-out-pull-requests-locally/):

```
go get -u github.com/vmware/govmomi
cd $GOPATH/src/github.com/vmware/govmomi
git fetch origin pull/813/head:vm-export 
git checkout vm-export
go install github.com/vmware/govmomi/govc
```

Destination is the first (non flag) argument, see the "Examples" section of `govc vm.export -h`

**Comment by SudarshanSudie** [comment]
Followed the same way of building govc , tried again with the set of steps that you had posted , seems to build just fine , but when I run "govc vm.export -h" or "govc vm.export -vm "vm-name" "/destination/path" , doesnt seem to do anything. 
Throws up a list of all functions that govc has.

Am i missing anything ?

**Comment by dougm** [comment]
Is `$GOPATH/bin` in your `$PATH` ?

```console
% md5sum $(which govc) $GOPATH/bin/govc                                                                                                                                                                                                 
805ccf3000d1645505697c77d26349e6  /home/dougm/bin/govc
805ccf3000d1645505697c77d26349e6  /home/dougm/bin/govc
```

**Comment by SudarshanSudie** [comment]
There was a small mistake in my setup , got that working now. So here's my next issue , so if my network bandwidth is X , then I seem to be using only 10% of X. For example - If I use my network capacity completely , then I should be able to transfer 15GB in 100 seconds. But , I see right now it takes abut 15 minutes for the same. I am thinking this can be because of two reasons,

1) VmWare writes the exported disk to their side and then we get to the destination location , in this case , there are 2 writes , once on their side and once on the destination , can we reduce this to once ?
2) Something to do with NFClease , or the way we write the packets of data on our side. (Similar to chunk_size in pyvmomi export.vm) , is there a way to optimize this way of reading or writing ?

If its none of the above and a totally different reason , kindly do guide me on that too. 

Otherwise , seems like the vm.export is working , we could skip the .iso files (from widnows machines) as exporting them is just a waste of network bandwidth.

Thanks a lot @dougm

**Comment by dougm** [comment]
Don't think there are 2 writes, even if there were there's nothing that govmomi can do about it.
Do you have any comparisons to export via ovftool or pyvmomi?

We do have some control over the chunk size, currently it is 32K via Go's io.Copy.

**Comment by SudarshanSudie** [comment]
`for block in response.iter_content(chunk_size=2048):`
So , the content of response from requests.get is iterated over by that chunks size , increasing the chunk size saw extra usage of memory but was faster (did not starve the memory). I was hoping to achieve similar results in govmomi , by basically changing over chunk size.

Any idea as to how to go about it ? Is changing io.Copy's chunk size advisable ?

**Comment by dougm** [comment]
Don't know if it'll help much, but you can experiement here:

```diff
modified   vim25/soap/client.go
@@ -680,7 +680,8 @@ func (c *Client) WriteFile(file string, src io.Reader, size int64, s progress.Si
 		}()
 	}
 
-	_, err = io.Copy(fh, r)
+	buf := make([]byte, 2*1024)
+	_, err = io.CopyBuffer(fh, r, buf)
 
 	cerr := fh.Close()
```

**Comment by ardrigh** [comment]
Having an `export.ov{a,f}` function would be a great alternative to ovftools, especially for building smaller Docker images to use.

**Comment by dougm** [comment]
@ardrigh and others interested could you give some examples of the ovftool commands you've been using to export VMs?  Examples of how you'd like it to look from a govc perspective would be great too.  While PR #805 is functional, I hadn't used ovftool to export VMs myself before and want to make sure we have a good UX before merging.  Thanks!

**Comment by ardrigh** [comment]
For our particular use cases:

### Examples
First method is a shell script for VM backup. 

We have a Docker image with VMware cli and ovftools installed. The Docker image needs CentOS base due to the system lib requirements. Docker image runs a shell script which powers off a vm, runs the export using ovftools, then powers on the vm.

The shell command:
```
ovftool --noImageFiles -dm=thin --disableVerification --noSSLVerify --overwrite vi://${VCSA_USER}:${VCSA_PASS}@${VCSA_HOST}/$DATACENTER/vm/${NAME} /mnt/$NAME.ova
```

Second method is using [Packer](https://packer.io) build with the [vmware-iso](https://www.packer.io/docs/builders/vmware-iso.html) builder - it exports the file using ovftools from an ESXi server to a local OVA file. 

We've just started looking at Packer to replace manual maintenance of the 'golden image' OVA files we have. The Packer builder moves our 'golden image' into a few text files - i.e. everything as code.

So having export functions in `govc` will allow us to look at replacing the first method almost entirely with `govc`, and provides a few options for other tools like Packer to take advantage of.

### Usage
In terms of the usage of an `export` function - I would expect similar to the import, but in reverse.

For testing I set the environment variables.
```  
GOVC_DATASTORE=dsname
GOVC_INSECURE=1
GOVC_PASSWORD=fakepassword
GOVC_URL=https://vsphere.example.com/sdk
GOVC_USERNAME=example
```
To import, I would run `govc import.ova path/to/local/ova` 

To export, I would _think_ to run `govc export.ova name_of_vm_or_vmid`

Method to specify export path could be in OPTIONS.

Some `ovftools` options that can be useful:
`--chunkSize`
`--compress`
`--noImageFiles`
`--overwrite`
`--skipManifestGeneration`


Note: Packer has an open ticket for [vSphere API support](https://github.com/hashicorp/packer/issues/4526) which it looks like the preference is to use the library proper, but using `govc` instead of `ovftools` did appear in one of the PRs.

**Comment by dougm** [comment]
@ardrigh very helpful, thanks for the details!

**Comment by dougm** [comment]
I updated the PR, the command is now called `export.ovf`.  Skipping `export.ova` for now - since we don't know the disk sizes ahead of time, we can't write the tar header, which means writing temp files.  Easy enough to create one: `(cd vm-foo && tar -cf ../vm-foo.ova .)`

Looks like `chunkSize` isn't supported anymore: https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2148588

Haven't looked at `compress` yet.

The `-f` flag will overwrite.

No manifest is generated by default, but you can use `-sha 256` (sha 1, 256 or 512) to create one.
