### ISSUE TITLE
Query on calling enableForkParent API

### ISSUE THREAD

**Issue by lox** [vmware/govmomi#761]
I'm experimenting with the VMFork APIs in vSphere. I'm trying to figure out how I'd use govmomi to call the `enableForkParent` on a `VirtualMachine` MOB. Any suggestions for how I'd do this? I understand it's a non-supported API, I'm just looking for a way to use govmomi to invoke it.

**Comment by lox** [comment]
More details here: https://www.higebu.com/2016-04-27-vmfork-using-mob-en.html

**Comment by dougm** [comment]
@lox you mentioned in slack you figured this out, anything you can share?  Also note that you can use the SOAP API too, but the types aren't generated.  See object/authorization_manager_internal.go and object/virtual_disk_manager_internal.go for examples.

**Comment by lox** [comment]
Thanks, I ended up just copying the generated types:

https://github.com/lox/govmomi-vmfork/blob/master/internal/types/types.go

**Comment by dougm** [comment]
@lox cool!  I'll close this issue for now then.  We certainly do want to include vmfork in govmomi at some point, but the internal APIs continue change.

**Comment by lox** [comment]
Do they actually change? It seems like they have been stable for quite some time. I get the impression VMWare has largely lost interest in VMFork.

**Comment by dougm** [comment]
Interest hasn't been lost, we need it in the vmware/vic project (and elsewhere).  I think it's just a matter of when and how it lands in "final"/public API form.  @hickeng and @mlh78750 may have some more details.

**Comment by lox** [comment]
I'd love to know if it works with macOS, if it doesn't it would save me a lot of trouble :)

**Comment by hickeng** [comment]
@lox If you can trigger the fork then the guest is pretty much immaterial from a base function perspective. Being able to update hardware MAC address, IPs, entropy, etc is where the guest specific behaviour come in - if this can be accomplished by scripts in the guest then there's a path forwards irrespective of direct support.

Triggering the fork from the guest was (is?) done as seen here: https://github.com/vmware/vic/blob/master/cmd/rpctool/main.go#L88
and eventually dependent on https://github.com/vmware/vmw-guestinfo/tree/master/bdoor which is architecture specific rather than OS.
