### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by shin-nien** [vmware/govmomi#803]
Hi, I'm having trouble with running govc and the examples. In all cases I keep getting `403 Forbidden` and running with -debug shows that the request goes out as:

```POST /sdk HTTP/1.1
Host: 10.x.x.x
Content-Type: text/xml; charset="utf-8"
Soapaction: urn:vim25/6.5
User-Agent: govc/0.15.0
```

Shouldn't the auth header be in the request?

I'm running the command as:

`GOVC_INSECURE=true ./govc_linux_amd64.15 ls -debug -u https://blah:blah@10.x.x.x/sdk`

with literally blah:blah to see if the auth header appears but it doesn't.

Any ideas?

**Comment by dougm** [comment]
I don't think httputil.DumpRequest is including the Cookie header.

If govc was able to login, you'll see it here: ` jq .SoapClient $(find ~/.govmomi/sessions -type f)`

Guessing there is something that's preventing any requests to /sdk, otherwise you'd be getting a SOAP response with a fault describing any login/permission issues, rather than a 403 response.

Do you get the expected 500 response or a 403 with this request: `curl --verbose -k -X POST https://10.x.x.x/sdk` ?

**Comment by shin-nien** [comment]
using the fqdn rather than IP worked
