### ISSUE TITLE
Specify a kickstart file for booting up a CentOS VM

### ISSUE THREAD

**Issue by rzubin** [vmware/govmomi#834]
I am trying to boot a centOS using a kickstart file.
What would be the best way to specify the location of the file , so that when I power on the VM it boots using that kickstart file
I saw this snippet in one of the examples 
```
govc device.floppy.add -vm $id > /dev/null
govc device.floppy.insert -vm $id $GOVC_TEST_IMG
govc device.boot -vm $id -delay 1000 -order floppy,cdrom,ethernet,disk
```
I tried to pass the kickstart file as $GOVC_TEST_IMG, but that didn't work.

**Comment by cseeger-epages** [comment]
is your img an iso file ? then try to use cdrom and not floppy, since floppy does not support iso's i think. 
```
govc device.cdrom.add -vm $id
govc device.cdrom.insert -vm $id $GOVC_TEST_IMG
govc device.boot -vm $id -delay 1000 -order cdrom,ethernet,disk
govc device.cdrom.eject -vm $id
```

**Comment by rzubin** [comment]
Hey @cseeger-epages,
I was trying to add the kickstart file to the floppy drive. That didn't work for me
Next I am going to try to bake the kickstart file in the the ISO and boot from the cdrom as you have suggested.

Zubin

**Comment by cseeger-epages** [comment]
@rzubin OK, we use this for our vm install pipeline and it works well for any kind of preseeded kickstart isos (centos 6/7, debian 7/8/9). 
Importend for automated install is to prevent a kickstart install boot loop.

Here you have some options:
- you can eject the iso file when done and before the system reboots
- you can change the boot order (this is only possible when the system is off, so you have to prevent the reboot) before rebooting
- if the system is fresh and nothing is on disk you can use boot order disk, cdrom, ethernet, because nothing is on disk it boots up the iso and on reboot its starts the freshly installed system (this is the cleanest way i think)

**Comment by rzubin** [comment]
Hey @cseeger-epages, thank you for the help and quick response.
I think ejecting the cdrom would be the easiest way to avoid the looping problem

**Comment by cseeger-epages** [comment]
Yes this works, but you may get the problem that if you eject the vm and the vm is powered on it gets stopped and asks in the web gui for confirmation. This sometimes happens and breaks the automation. I use this solution only for a reinstall because i did not find another working solution. Here is the code snipped i use in the Jenkins pipeline script:
```
sh '''#!/bin/bash -ex
govc device.cdrom.insert -ds "iso_images" -vm ${vm} isos/${iso}.iso;
govc device.boot -order cdrom,disk -vm ${vm};
sleep 5;
i-doit-go-automation/bin/govc vm.power -on ${vm};
sleep 20;
'''
try {
  sh "i-doit-go-automation/bin/govc device.cdrom.eject -vm ${params.vm}"
} catch (error) {
  sh '''#!/bin/bash -ex
  sleep 10;
  govc device.cdrom.eject -vm ${vm};
  '''
}
```
This actually works but its a bit nasty solution.

**Comment by rzubin** [comment]
@cseeger-epages I haven't reached that part yet but I have thought about it. I was going to implement a try  around one of the govc guest commands. As these need the root login and password that would be in the kickstart, if it is a success I think it would mean that the installation was a success and I can eject the cdrom.

**Comment by cseeger-epages** [comment]
@rzubin sounds interessting. Please give me a hint if this solution works.

**Comment by rzubin** [comment]
hey @cseeger-epages I am using the following command to check the OS is installed and it get an IP from dhcp before converting it to a template
```
govc vm.ip -wait 30m vm_name
```
Hopefully this helps you

Zubin

**Comment by cseeger-epages** [comment]
@rzubin hehe yeah im doing the same but 15m is enough. This solution forces you to install guest-os-vmware-tools because the IP will not recognised if no vmware-tools are installed but it works well for new installs but not for reinstall because of the boot loop.

**Comment by dkirrane** [comment]
@cseeger-epages have you manged to get this to work. How do you pass a kickstart file? I'm trying to install CentOS-7-x86_64-Minimal-1708.iso

**Comment by cseeger-epages** [comment]
Here is a snippet of our reinstall_vm jenkins job
```
govc device.cdrom.insert -ds "datastore_iso_images" -vm ${vm} isos/netboot/${iso}.iso;
govc device.boot -order cdrom,disk -vm ${vm};
sleep 5;
govc vm.power -on ${vm};
```
dont forget to change the `device.boot -order` back to normal after installation has finished or just
```
govc device.cdrom.eject -vm ${vm}
```
i force the eject 20 seconds after the installation has started since i only use netboot images and after initial stuff everything comes from the internet :)

**Comment by dkirrane** [comment]
@cseeger-epages just getting back to this.
I can create the vm with `govc vm.create -iso=ISOs/CentOS-7-x86_64-Minimal-1708.iso` but just wondering how to pass a kickstart

Can I upload both the `CentOS-7-x86_64-Minimal-1708.iso` and `kg.cfg` to a datastore and create a new vm from those? How do you pass the boot option `inst.ks=path/to/kg.cfg`.

**Comment by angystardust** [comment]
@dkirrane if you have your ks.cfg in a virtual floppy attached to the vm, you can try to add this to the boot parameters `inst.ks=hd:fd0:/ks.cfg`

**Comment by cseeger-epages** [comment]
@dkirrane we use [ipxe](http://ipxe.org) to build a kickstart iso file this pulls the cfg from a webserver and starts the install process.

**Comment by dougm** [comment]
Closing as stale - feel free to reopen if this is still an issue.
