### ISSUE TITLE
Finding VM's based on resource group

### ISSUE THREAD

**Issue by sorenh** [vmware/govmomi#992]
I've been struggling for days to find a way to find the equivalent of a list of VM's in the vSphere web client. I'm hoping you can help.

In the web client, I go to "Hosts and Clusters". I'm new to vSphere, so I don't know what all the different resources are called at the different levels. Please bear with me.

At the top level, I have just a single entry (the icon is the vSphere icon). Under that entry, I have a bunch of next-level entries (icons resemble a tall building and a shorter building). Under those entries, I have another bunch of entries (icons resemble three (tower chassis) servers). Under each of those entries, I have some entries whose icon is purple and blue pie chart. I guess that's a "resource pool"? Under there, I can click on a thing where it says "(NN) Virtual Machines".... It's this list of VM's that I need to find using `govc`. Ultimately, the goal is to power them off (if they're on) and delete them.

Can someone point me in the right direction?

**Comment by dougm** [comment]
If it is a nested `ResourcePool`, you're looking for the `vm` field, which is an array of `ManagedObjectReference`.  Two ways to get the field and convert to inventory path:

```console
% govc pool.info -json /dc-name/host/cluster-name/Resources/pool-name | jq -r '.ResourcePools[].Vm[] | join(":")' | xargs govc ls -L

% govc object.collect -s /dc-name/host/cluster-name/Resources/pool-name vm | tr ',' '\n' | xargs govc ls -L
```

But if it is the cluster root pool, rather than a nested resource pool, you can just use the cluster itself.  For example:

```console
% govc find /dc-name/host/cluster-name -type m -runtime.powerState poweredOn
```

Either way, just pipe the list of VMs to `govc vm.power -force -off`
